### ISSUE TITLE
index.py File not found [OS: Arch Linux]

### ISSUE THREAD

**Issue by dr03m** [Shugabuga/Silica#20]
Getting the following error when doing `python3 index.py` for the first time

```dro3m@hp-sleeper ~/Silica (master) [1]> python3 index.py
Silica Compiler 1.2.1
Traceback (most recent call last):
  File "index.py", line 229, in <module>
    main()
  File "index.py", line 193, in main
    DebianPackager.CreateDEB(tweak_data['bundle_id'], tweak_data['version'])
  File "/home/dro3m/Silica/util/DebianPackager.py", line 252, in CreateDEB
    os.remove(self.root + "temp/" + bundle_id + "/control")
FileNotFoundError: [Errno 2] No such file or directory: '/home/dro3m/Silica/util/../temp/com.ipadkid.ftt/control'
```

OS is Arch Linux, not sure what is going on here and this is my first time using Silica. 

Edit: I have check to make sure the files and directories exist and they do.  

Edit#2: Tried in a Linux Mint VM, same exact error.

Edit#3: Tried using a example package with no index.json and got this:
```dro3m@hp-sleeper ~/Silica (master)> python3 index.py
Silica Compiler 1.2.1
Traceback (most recent call last):
  File "index.py", line 229, in <module>
    main()
  File "index.py", line 55, in main
    tweak_release = PackageLister.GetTweakRelease()
  File "/home/dro3m/Silica/util/PackageLister.py", line 55, in GetTweakRelease
    with open(self.root + "Packages/" + tweakEntry + "/silica_data/index.json", "r") as content_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dro3m/Silica/util/../Packages/com.mdausch.exampletweak/silica_data/index.json'
```
This is under Arch this time. This script seems very broken or I'm just being dumb. 

Edit#4: Picture of the ../Packages Folder
![image](https://user-images.githubusercontent.com/53626883/79061956-9fa1a980-7c63-11ea-93c9-7c4f711aa4e0.png)

**Comment by Shugabuga** [comment]
Fixed in Silica 1.2.3.
