### ISSUE TITLE
Silica not able to create index.json, errors out but is able to move on to the next package.

### ISSUE THREAD

**Issue by dr03m** [Shugabuga/Silica#23]
```
dro3m@DESKTOP-OD8LPNR:~/Downloads/Silica> sudo python3 index.py
Silica Compiler 1.2.2
It seems like the package "eggcrypt" is not configured. Let's set it up!
Extracting data from DEB...
What is the original author's email address?
What is the maintainer's email address?
What is the lowest iOS version the package works on? 12
What is the highest iOS version the package works on? 13.5
Should this package be featured on your repo? (true/false) true
What would you like this package's tint color to be? To keep it at the default, leave this blank:
All done! Please look over the generated "index.json" file and consider populating the "silica_data" folder with a description, screenshots, and an icon.
Traceback (most recent call last):
  File "index.py", line 225, in <module>
    main()
  File "index.py", line 49, in main
    DebianPackager.CheckForSilicaData()
  File "/home/dro3m/Downloads/Silica/util/DebianPackager.py", line 453, in CheckForSilicaData
    os.remove(self.root + "Packages/" + folder + "/silica_data/scripts/Control")
FileNotFoundError: [Errno 2] No such file or directory: '/home/dro3m/Downloads/Silica/util/../Packages/eggcrypt/silica_data/scripts/Control'
dro3m@DESKTOP-OD8LPNR:~/Downloads/Silica>
```

This happens both on WSL Ubuntu 20.04 and OpenSUSE Tumbleweed.

Update: I created a folder on my C drive and placed Silica there. Everything was all fine until I got to one package. Not sure if it's the package or Silica or the folder itself:

```
Silica Compiler 1.2.2
It seems like the package "eggcrypt" is not configured. Let's set it up!
Extracting data from DEB...
What is the original author's email address?
What is the maintainer's email address?
What is the lowest iOS version the package works on? 13
What is the highest iOS version the package works on? 13.5
Should this package be featured on your repo? (true/false) true
What would you like this package's tint color to be? To keep it at the default, leave this blank:
All done! Please look over the generated "index.json" file and consider populating the "silica_data" folder with a description, screenshots, and an icon.
Traceback (most recent call last):
  File "index.py", line 225, in <module>
    main()
  File "index.py", line 178, in main
    + "/DEBIAN")
  File "/usr/lib/python3.7/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('/mnt/c/WSL/Silica_egg/Packages/eggcrypt/silica_data/scripts', '/mnt/c/WSL/Silica_egg/temp/com.castyte.eggcrypt/DEBIAN', "[Errno 13] Permission denied: '/mnt/c/WSL/Silica_egg/temp/com.castyte.eggcrypt/DEBIAN'")]
```

Updated: Updated to WSL 2 and reran the script, and go this error:

```
dpkg-deb: error: control directory has bad permissions 777 (must be >=0755 and <=0775)
- DPKG Error! -
dpkg-deb failed to run. This could be due to a faulty system configuration.
```

**Comment by dr03m** [comment]
Switch back to macOS and now it works fine.
