### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 2218: ordinal not in range(256)

### ISSUE THREAD

**Issue by Worf1337** [Shugabuga/Silica#38]
Hi,

I'm compiling a repo with Silica, and getting an error every time. I'm putting it below.

`Silica Compiler 1.2.2
Traceback (most recent call last):
  File "index.py", line 225, in <module>
    main()
  File "index.py", line 125, in main
    PackageLister.CreateFile("docs/index.html", index_html)
  File "/root/Documents/Silica/util/PackageLister.py", line 25, in CreateFile
    text_file.write(contents)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 2218: ordinal not in range(256)
`

If anyone could help that would be appreciated. Thanks!

**Comment by Worf1337** [comment]
alright i've ruled it to just be that my linux setup is fucked. worked after wipe.
