### ISSUE TITLE
Errors by running index.py

### ISSUE THREAD

**Issue by neumaif02** [Shugabuga/Silica#6]
`Silica Compiler 1.0.0
Traceback (most recent call last):
  File "/home/felix/Schreibtisch/Silica-master/index.py", line 214, in <module>
    main()
  File "/home/felix/Schreibtisch/Silica-master/index.py", line 114, in main
    index_html = DepictionGenerator.RenderIndexHTML()
  File "/home/felix/Schreibtisch/Silica-master/util/DepictionGenerator.py", line 288, in RenderIndexHTML
    replacements = DepictionGenerator.RenderDataHTML(self)
  File "/home/felix/Schreibtisch/Silica-master/util/DepictionGenerator.py", line 331, in RenderDataHTML
    data['repo_carousel'] = DepictionGenerator.CarouselEntryList(self, tweak_release)
  File "/home/felix/Schreibtisch/Silica-master/util/DepictionGenerator.py", line 465, in CarouselEntryList
    featured_int = random.randint(0,(len(tweak_release)-1))
  File "/usr/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.7/random.py", line 200, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)
`

**Comment by Shugabuga** [comment]
What is in the `Packages` folder?

**Comment by neumaif02** [comment]
Added the folder with the deb file, now works.

**Comment by Shugabuga** [comment]
[I'll look into providing a more clear warning if this happens again.](https://github.com/Shugabuga/Silica/projects/1#card-21877901).

**Comment by Shugabuga** [comment]
A more clear error message will appear in Silica 1.1.0.
